import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import { getAllFilesFrontMatter } from "@/lib/mdx";
import styles from "../styles/Home.module.css";

export default function Blog({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Aprende JavaScript con Carlos Azaustre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>carlosazaustre.es</h1>

        <div className={styles.grid}>
          {posts.map((post) => (
            <Link href={post.slug} key={post.slug}>
              <a className={styles.card}>
                <h2>{post.title} &rarr;</h2>
                <p>{post.date}</p>
              </a>
            </Link>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const posts = await getAllFilesFrontMatter("posts");
  return {
    props: { posts },
  };
}
